/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CleaningRouteImport } from './routes/cleaning'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as EdaRouteImport } from './routes/eda'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as UploadRouteImport } from './routes/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CleaningRoute = CleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const EdaRoute = EdaRouteImport.update({
  id: '/eda',
  path: '/eda',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cleaning': typeof CleaningRoute
  '/dataset': typeof DatasetRoute
  '/eda': typeof EdaRoute
  '/explainability': typeof ExplainabilityRoute
  '/insights': typeof InsightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reports': typeof ReportsRoute
  '/training': typeof TrainingRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cleaning': typeof CleaningRoute
  '/dataset': typeof DatasetRoute
  '/eda': typeof EdaRoute
  '/explainability': typeof ExplainabilityRoute
  '/insights': typeof InsightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reports': typeof ReportsRoute
  '/training': typeof TrainingRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/cleaning': typeof CleaningRoute
  '/dataset': typeof DatasetRoute
  '/eda': typeof EdaRoute
  '/explainability': typeof ExplainabilityRoute
  '/insights': typeof InsightsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/reports': typeof ReportsRoute
  '/training': typeof TrainingRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/cleaning'
    | '/dataset'
    | '/eda'
    | '/explainability'
    | '/insights'
    | '/leaderboard'
    | '/reports'
    | '/training'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/cleaning'
    | '/dataset'
    | '/eda'
    | '/explainability'
    | '/insights'
    | '/leaderboard'
    | '/reports'
    | '/training'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/cleaning'
    | '/dataset'
    | '/eda'
    | '/explainability'
    | '/insights'
    | '/leaderboard'
    | '/reports'
    | '/training'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CleaningRoute: typeof CleaningRoute
  DatasetRoute: typeof DatasetRoute
  EdaRoute: typeof EdaRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  InsightsRoute: typeof InsightsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ReportsRoute: typeof ReportsRoute
  TrainingRoute: typeof TrainingRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaning': {
      id: '/cleaning'
      path: '/cleaning'
      fullPath: '/cleaning'
      preLoaderRoute: typeof CleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eda': {
      id: '/eda'
      path: '/eda'
      fullPath: '/eda'
      preLoaderRoute: typeof EdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CleaningRoute: CleaningRoute,
  DatasetRoute: DatasetRoute,
  EdaRoute: EdaRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  InsightsRoute: InsightsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ReportsRoute: ReportsRoute,
  TrainingRoute: TrainingRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
